versions: "3.8"
services:

  store-web:
    build: ./store-web
    container_name: store-web
    tty: true
    # restart: unless-stopped
    ports:
      - '3000:4000'
    # issues when adding volumes
    networks: 
      - store-network

  store-api:
    build: ./store-api
    container_name: store-api
    # restart: unless-stopped
    ports:
      - '3001:4001'
    depends_on:
      - store-db
    networks: 
      - store-network

  store-db:
    build: ./store-db
    container_name: store-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    networks: 
      - store-network
    volumes:
    # here we create and link persistant postgres database, so if image is deleted the data is not lost
      - db:/var/lib/postgresql/data:Z

    
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - store-web
      - store-api
    networks: 
      - store-network

volumes:
  db:
    driver: local

networks: 
  store-network:
    driver: bridge
