versions: "3.8"
services:

  store-web:
    build: ./store-web
    container_name: store-web
    tty: true
    # restart: unless-stopped
    ports:
      - '4000:4000'
    # issues when adding volumes
    # volumes:
    #   - ./store-web:/app:Z
    #   - /app/node_modules
    # networks: 
    #   - store-network

  store-api:
    build: ./store-api
    container_name: store-api
    # restart: unless-stopped
    ports:
      - '4001:4001'
    # volumes:
    #   - ./store-api:/app:Z
    #   - /app/node_modules
    depends_on:
      - store-db
    # networks: 
    #   - store-network

  store-db:
    build: ./store-db
    container_name: store-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    # networks: 
    #   - store-network
    volumes:
    # here we create and link persistant postgres database, so if image is deleted the data is not lost
      - db:/var/lib/postgresql/data:Z

    
  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   # restart: unless-stopped
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - store-web
  #     - store-api
  #   networks: 
  #     - store-network

volumes:
  db:
    driver: local

# networks: 
#   store-network:
#     driver: bridge

